### PR TITLE
Login: Friendly error message if email is incorrect

### LINKED ISSUE #49: 500 error on login if no user was found for given email address
**Describe the bug**
If you haven't run the seeds in the backend and you try to log in through your frontend you see:
*Error: GraphQL error: Cannot read property '_fields' of undefined*

**EDIT**: It happens if no user was found for a given email. You can also run the seed data and use a non-existing email address to reproduce the error.

**To Reproduce**
1. Clone the repository, run `docker-compose up`
2. Visit http://localhost:4000/
3. Post following data to endpoint:
```graphql
mutation ($email: String!, $password: String!) {
  login(email: $email, password: $password) {
		token
  }
}
```
with query variables:
```json
{
  "email": "admin@example.org",
   "password": "1234"
}
```
4. See error:
```json
{
  "data": {
    "login": null
  },
  "errors": [
    {
      "message": "Cannot read property '_fields' of undefined",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "login"
      ]
    }
  ]
}
```

**Expected behavior**
4. See error:
```json
{
  "data": {
    "login": null
  },
  "errors": [
    {
      "message": "There is no user with this email address.",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "login"
      ]
    }
  ]
}
```

**Additional context**
This is how it looks from the frontend:
screenshot_2018-12-04 human connection - human connection

### PR DESCRIPTION
**Pull request by roschaefer**
close #49 

ping @kachulio1

### CODE REVIEW

**Comment by appinteractive** [comment]
Please use ~ for pinning package versions to prevent unintended upgrades.

**Comment by appinteractive** [comment]
What is the reason you replaced mocha with jest?

**Comment by roschaefer** [comment]
@appinteractive from the [commit message](https://github.com/Human-Connection/Nitro-Backend/pull/88/commits/eaef67fad3c99e0c2c26dc1ee5244fc825dbc4ba):
```
To have a consisten test runner in both repos (Nitro-Web and
Nitro-Backend)
```

**Comment by appinteractive** [comment]
Wow something is really broken with the test files and linting. @roschaefer

**Comment by Kachulio1** [comment]
looks like neo4j service is not started in Travis

File: src/seed/factories/users.js [hunk 1]
```diff
@@ -0,0 +1,36 @@
...
+    name: faker.name.findName(),
+    email: faker.internet.email(),
+    password: '1234',
+    avatar: faker.internet.avatar()
+  }
+  const {
+    name,
+    email,
+    password,
+    avatar
```
[the remark this answers is not in the document]
Comment (roschaefer) [reply src/seed/factories/users.js]: Can you show me how?

[the remark this answers is not in the document]
Comment (roschaefer) [reply src/seed/factories/users.js]: Got it
```js
export default function (params){
  const {
    name = faker.name.findName(),
    email = faker.internet.email(),
    password =  '1234',
    avatar = faker.internet.avatar()
  } = params
```
from here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment#Default_values_2

File: src/seed/factories/users.js [hunk 2]
```diff
@@ -0,0 +1,36 @@
...
+  return `
+    mutation {
+      u1: CreateUser(
+        id: "u1",
+        name: "${name}",
+        password: "${password}",
+        email: "${email}",
+        avatar: "${avatar}",
+        role: admin,
+        disabled: false,
```
[the remark this answers is not in the document]
Comment (roschaefer) [reply src/seed/factories/users.js]: That's alright for the moment, I would say.

[the remark this answers is not in the document]
Comment (appinteractive) [reply src/seed/factories/users.js]: But not for seeding as we need different kinds of users. And I think we should use the factories also for seeding so...

File: src/seed/factories/users.js (hunk 1 above)
[the remark this answers is not in the document]
Comment (appinteractive) [reply src/seed/factories/users.js]: @roschaefer for the testing I did the behavior of that solutions leads to defaults only for values given, not for empty ones. I don’t think that’s intended!?

File: src/seed/factories/users.js [hunk 3]
```diff
@@ -0,0 +1,30 @@
+import faker from 'faker'
+
+export default function (params) {
+  const {
```
Comment (appinteractive) [inline src/seed/factories/users.js]: @roschaefer use this one to get propper defaults!

```js
  params = {
    name: faker.name.findName(),
    email: faker.internet.email(),
    password: '1234',
    avatar: faker.internet.avatar()
     ...params
  }
```

File: src/seed/factories/users.js (hunk 1 above)
[the remark this answers is not in the document]
Comment (appinteractive) [reply src/seed/factories/users.js]:
```
params = {
    name: faker.name.findName(),
    email: faker.internet.email(),
    password: '1234',
    avatar: faker.internet.avatar()
     ...params
  }
```

File: src/seed/factories/users.js (hunk 3 above)
Comment (roschaefer) [reply src/seed/factories/users.js]: I double checked empty values and given values and they work OK. I cannot reproduce that behaviour. Can you explain it maybe? Probably I did something wrong?

Comment (appinteractive) [reply src/seed/factories/users.js]: @roschaefer https://runkit.com/appinteractive/nitro-backend-pull-88

Comment (appinteractive) [reply src/seed/factories/users.js]: But it seems to work now.

**Comment by appinteractive** [comment]
Neo4j 3.2 is the wrong version! We use 3.5 and need the apoc plugin. Therefore we need our container with that setup.

**Comment by roschaefer** [comment]
@appinteractive see my latest commit. We don't need neo4j at all on Travis.

**Comment by appinteractive** [comment]
Yeah but @mattwr18 runs the wrong version locally.

**Comment by roschaefer** [comment]
I think @mattwr18 posted an excerpt of the log of our build server.

**Comment by mattwr18** [comment]
it was the output of the build @appinteractive @roschaefer 
@roschaefer currently the docker build is getting stuck here 
```
yarn install v1.12.3
[1/4] Resolving packages...
error Your lockfile needs to be updated, but yarn was run with `--frozen-lockfile`.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
ERROR: Service 'backend' failed to build: The command '/bin/sh -c yarn install --frozen-lockfile --non-interactive' returned a non-zero code: 1
```
I'll have to have a debug later to see what is happening, then I'll run the tests through `docker-compose`

**Comment by appinteractive** [comment]
Then the build server had the wrong version. 😬

File: src/graphql-schema.test.js [hunk 4]
```diff
@@ -15,8 +15,9 @@ beforeEach(async () => {
   getHost = () => `http://127.0.0.1:${port}`
 })
 
-afterEach(async () => {
+afterAll(async (done) => {
   await app.close()
+  done()
```
Comment (appinteractive) [inline src/graphql-schema.test.js]: Is that some jest/mocha magic?

Comment (Kachulio1) [reply src/graphql-schema.test.js]: Yes, but I don't think it will work. because of this [graphql-yoga](https://github.com/prisma/graphql-yoga/issues/404) you can't close the server from `app` you can only close it in the `server variable` according to the link

**Comment by mattwr18** [comment]
Also, on the Travis CI issues, they suggest to use `--forceExit`, which seems to have resolved it, at least for now

File: src/graphql-schema.test.js (hunk 4 above)
Comment (roschaefer) [reply src/graphql-schema.test.js]: The `done` callback is normally used to test async behaviour and callbacks. You can call `done()` in your callback and the test will not pass until it `done` reached. If a test case has no `done` in the method argument list, the method body will be executed and the test will pass if no error was raised. To prevent this you can use `done` callback.

If this does not fix the build, can we maybe revert it?

@Kachulio1 `git revert 3a9cb31e1f6039aecd428b2fc250b4b88a18ccfa` ?

Comment (roschaefer) [reply src/graphql-schema.test.js]: I did that just now

**Comment by roschaefer** [comment]
yay :tada: 

But after the party we should try to find a way for the `test` and `development` database for neo4j. We can also mention the neo4j core team on twitter, they asked us to mention them if we need help.
