### PR TITLE
FIX #49 capture error in readable format with try and catch

### LINKED ISSUE #49: 500 error on login if no user was found for given email address
**Describe the bug**
If you haven't run the seeds in the backend and you try to log in through your frontend you see:
*Error: GraphQL error: Cannot read property '_fields' of undefined*

**EDIT**: It happens if no user was found for a given email. You can also run the seed data and use a non-existing email address to reproduce the error.

**To Reproduce**
1. Clone the repository, run `docker-compose up`
2. Visit http://localhost:4000/
3. Post following data to endpoint:
```graphql
mutation ($email: String!, $password: String!) {
  login(email: $email, password: $password) {
		token
  }
}
```
with query variables:
```json
{
  "email": "admin@example.org",
   "password": "1234"
}
```
4. See error:
```json
{
  "data": {
    "login": null
  },
  "errors": [
    {
      "message": "Cannot read property '_fields' of undefined",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "login"
      ]
    }
  ]
}
```

**Expected behavior**
4. See error:
```json
{
  "data": {
    "login": null
  },
  "errors": [
    {
      "message": "There is no user with this email address.",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "login"
      ]
    }
  ]
}
```

**Additional context**
This is how it looks from the frontend:
screenshot_2018-12-04 human connection - human connection

### PR DESCRIPTION
**Pull request by Gerald1614**
just added a try and catch error on resolver to change error message to more readable one. I chose on purpose to send only one unified message as a best practise not to give hints to potential hackers to know if user or password is wrong.

### CODE REVIEW

File: src/graphql-schema.js [hunk 1]
```diff
@@ -95,32 +96,33 @@ export const resolvers = {
...
+        const res = await session.run('MATCH (u:User {email: "' + email + '"}) RETURN u.id, u.slug, u.name, u.avatar, u.email, u.password, u.role LIMIT 1')
+        const u = res.records[0]._fields ? zipObject([
+          'id',
+          'slug',
+          'name',
+          'avatar',
+          'email',
+          'password',
+          'role'
+        ], res.records[0]._fields) : null
```
Comment (roschaefer) [inline src/graphql-schema.js]: I would check if `res.records.length <= 0` rather than `try + catch`.

Comment (Gerald1614) [reply src/graphql-schema.js]: the try and catch also captures the situation where the user exists but password is not validated. we could switch from try and catch to test if res.records.length <=0 but in that case we would need also to cover the case where the password is wrong. another reason I see is that we are using res.records[0]._fields to retrieve the data from the DB but in other cases we are using record.get.  the try and catch provides a simple and unique way to catch errors while the other method will be specific to every resolver. what is wrong with try and catch ?

File: src/graphql-schema.js [hunk 2]
```diff
@@ -95,32 +96,33 @@ export const resolvers = {
...
+        if (u) {
+          if (await bcrypt.compareSync(password, u.password)) {
+            delete u.password
+            u.avatar = fixUrl(u.avatar)
+            return Object.assign(u, {
+              token: generateJwt(u)
+            })
+          }
+          session.close()
+          throw new Error('Incorrect username or password.')
```
Comment (appinteractive) [inline src/graphql-schema.js]: Please also use the AuthenticationError here. Then it should be fine.
```suggestion
           throw new AuthenticationError('Incorrect username or password.')
```

File: src/graphql-schema.js [hunk 3]
```diff
@@ -95,32 +96,33 @@ export const resolvers = {
...
+            return Object.assign(u, {
+              token: generateJwt(u)
+            })
+          }
+          session.close()
+          throw new AuthenticationError('Incorrect username or password.')
         }
         session.close()
-        throw new Error('Incorrect password.')
+      } catch (error) {
```
Comment (appinteractive) [inline src/graphql-schema.js]: Don`t we need to also close the session in the catch block?

File: src/graphql-schema.js [hunk 4]
```diff
@@ -95,32 +96,33 @@ export const resolvers = {
...
+        throw new AuthenticationError('Incorrect username or password.')
```
Comment (appinteractive) [inline src/graphql-schema.js]:
```suggestion
        session.close()
        throw new AuthenticationError('Incorrect username or password.')
```

Comment (Gerald1614) [reply src/graphql-schema.js]: that's a good question. i just went to the doc of the neo4j driver (https://www.npmjs.com/package/neo4j-driver) and they do not seem to close the session on error. they do it when the promise get resolved but they seem not to close it on error. i coudl add one but i can not tell if it is required or not.

Comment (Gerald1614) [reply src/graphql-schema.js]: Hi, I have been lloking at what is done and i wanted to suggest to change the way we address login.  in fact I changed many things:

1. I remove usage of Lodash zipObejct as ES6 is doign that now,
2. I changed the cypher to use the key user so it is easier to query the result with a record.get
3. I used .then and closed the session at the beigining (so we are sure the session is closed whatever happens
4 . I am throwign error if user doe snot exist or if password is wrong in else statements.
I am not saying we shoudl use this way, but I think it is cleaner. 
I coudl created a new commit for this pull request but here is ho the new code would look like:
```      const session = driver.session()
      return session.run(
        'MATCH (user:User {email: "' + email + '"}) ' +
        'RETURN user {.id, .slug, .name, .avatar, .email, .password, .role} as user LIMIT 1')
        .then(async (result) => {
          session.close()
          const [currentUser] = await result.records.map(function (record) {
            console.log(record.get('user'))
            return record.get('user')
          })
          if (currentUser) {
            if (await bcrypt.compareSync(password, currentUser.password)) {
              delete currentUser.password
              currentUser.avatar = fixUrl(currentUser.avatar)
              return Object.assign(currentUser, {
                token: generateJwt(currentUser)
              })
            } else throw new AuthenticationError('Incorrect username or password.')
          } else throw new AuthenticationError('Incorrect username or password.')
        })```

Comment (appinteractive) [reply src/graphql-schema.js]: For readability we should never write cascaded code. (If Inside if inside then)

Try to keep max level of one, not three as the complexity rises very quick and becomes unmaintainable for others.

Comment (Gerald1614) [reply src/graphql-schema.js]: agreed. i will provide a new version.

Comment (Gerald1614) [reply src/graphql-schema.js]: a new commit with changes has been submittted

File: src/graphql-schema.js [hunk 5]
```diff
@@ -95,32 +95,24 @@ export const resolvers = {
...
-        'role'
-      ], res.records[0]._fields) : null
-      if (u) {
-        if (await bcrypt.compareSync(password, u.password)) {
-          delete u.password
-          u.avatar = fixUrl(u.avatar)
-          return Object.assign(u, {
-            token: generateJwt(u)
+      return session.run(
+        'MATCH (user:User {email: "' + email + '"}) ' +
```
Comment (roschaefer) [inline src/graphql-schema.js]: @Gerald1614 do you know if we have a cypher injection vulnerability here?

Comment (appinteractive) [reply src/graphql-schema.js]: I opened a seperate Issue for the Injection/Sanitization issue. #95

Comment (Gerald1614) [reply src/graphql-schema.js]: I did not pay attention because this piece was already there.  but we shoudl use varibales to inject data in teh query. the request should look like:
```'MATCH (user:User {email: $userEmail}) ' +
        'RETURN user {.id, .slug, .name, .avatar, .email, .password, .role} as user LIMIT 1', { userEmail: email })```

Comment (Gerald1614) [reply src/graphql-schema.js]: this is the recommended way when dealing with cypher and variables. we should use this.  Graphql playground includes a place to inject those data as well.

**Comment by Gerald1614** [comment]
HI, i do not know if you can pause the process as i wanted to commit one latest change regarding the injection of variables (as mentioend in previous post) i really think we should use the new code. it is ready but i coudl not push it as the merge is udner process. let me know if we can defer the PR just a bit so I can submit the last commit or if I will have to submit a new PR for that

**Comment by appinteractive** [comment]
@Gerald1614 I think you just need to pull the latest change before pushing!? Or what do you mean exactly by „in process“? I just merged the  current master in.

**Comment by Gerald1614** [comment]
let me check

**Comment by Gerald1614** [comment]
@appinteractive i just checked and everythign is working as expected on my side both when using the ui or graphql playground. if both are correct we are logged in, if one of the two is wrong we receive a unqiue message saying "Incorrect user or password " you get a different behavior ?
I have a call in 50mn but if you have 20mn we could do a video conf now if you can

**Comment by roschaefer** [comment]
@appinteractive regarding your latest review: @Gerald1614 's fix is making the tests pass for the following test cases:
1) correct email + password
2) wrong email + password
3) wrong email + wrong password

So I think it might be some stale code on your machine?
